# This is a basic workflow to help you get started with Actions

name: Github Actions

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ stage ]
  pull_request:
    branches: [ latest, sha ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - name: Checkout
        uses: actions/checkout@2.0

      - name: Install Dependencies    #npm install
        run: npm install

      - name: Build                   # React Build
        run: npm run build
      -
        name: Docker meta
        id: docker_meta
        uses: crazy-max/ghaction-docker-meta@v1
        with:
          images: yt-api
          tag-semver: |
            {{version}}
            {{major}}.{{minor}}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      -
        name: Login to DockerHub
        uses: docker/login-action@v1 #use action
        with: #action input
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          build_args: REACT_APP_KEY=${{ secrets.REACT_APP_KEY }} 
            REACT_APP_SOCIAL=${{ secrets.REACT_APP_SOCIAL }}
            REACT_APP_VERIFY=${{ secrets.REACT_APP_VERIFY }}
            REACT_APP_CHANNEL_SEARCH=${{ secrets.REACT_APP_CHANNEL_SEARCH }}
            REACT_APP_CHANNEL_BASIC=${{ secrets.REACT_APP_CHANNEL_BASIC }} 
            REACT_APP_CHANNEL_INFO=${{ secrets.REACT_APP_CHANNEL_INFO }}
            REACT_APP_CHANNEL_SUMMARY=${{ secrets.REACT_APP_CHANNEL_SUMMARY }} 
            REACT_APP_VIDEO_LIST=${{ secrets.REACT_APP_VIDEO_LIST }}
            REACT_APP_VIDEO_SUMMARY=${{ secrets.REACT_APP_VIDEO_SUMMARY }} 
            REACT_APP_VIDEO_INFO=${{ secrets.REACT_APP_VIDEO_INFO }}
      -
        name: Build and push
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./Dockerfile
          platforms: linux/amd64
          push: true
          tags: ${{ steps.docker_meta.outputs.tags }}
          labels: ${{ steps.docker_meta.outputs.labels }}
